(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(Info-fit-frame-flag nil)
 '(ansi-color-names-vector
   ["#1B2229" "#ff6c6b" "#98be65" "#ECBE7B" "#51afef" "#c678dd" "#46D9FF" "#DFDFDF"])
 '(anzu-cons-mode-line-p nil)
 '(avy-case-fold-search t)
 '(avy-timeout-seconds 0.3)
 '(column-number-mode t)
 '(company-global-modes '(emacs-lisp-mode c-mode c++-mode))
 '(company-idle-delay nil)
 '(compilation-always-kill t)
 '(compilation-ask-about-save nil)
 '(compilation-context-lines 10)
 '(compilation-scroll-output 'first-error)
 '(compilation-skip-threshold 2)
 '(custom-buffer-done-function 'kill-buffer)
 '(custom-file "~/.emacs.d/settings.el")
 '(custom-safe-themes
   '("a24c5b3c12d147da6cef80938dca1223b7c7f70f2f382b26308eba014dc4833a" "3c83b3676d796422704082049fc38b6966bcad960f896669dfc21a7a37a748fa" default))
 '(delete-by-moving-to-trash t)
 '(ecb-options-version "2.50")
 '(fci-rule-color "#2f2f2f")
 '(flymake-tslint-args nil)
 '(global-auto-complete-mode t)
 '(global-auto-revert-mode t)
 '(global-font-lock-mode t nil (font-lock))
 '(indent-tabs-mode nil)
 '(inhibit-startup-echo-area-message "")
 '(inhibit-startup-screen t)
 '(initial-scratch-message "")
 '(ispell-extra-args '("--sug-mode=fast"))
 '(jdee-db-active-breakpoint-face-colors (cons "#1B2229" "#51afef"))
 '(jdee-db-requested-breakpoint-face-colors (cons "#1B2229" "#98be65"))
 '(jdee-db-spec-breakpoint-face-colors (cons "#1B2229" "#3f444a"))
 '(line-number-mode t)
 '(load-prefer-newer t)
 '(lsp-enable-eldoc nil)
 '(lsp-inhbit-message t)
 '(make-backup-files nil)
 '(mouse-wheel-progressive-speed nil)
 '(mouse-wheel-scroll-amount '(1 ((shift) . 5) ((control))))
 '(nlinum-format "%5d ")
 '(persistent-scratch-autosave-interval 30)
 '(projectile-enable-caching t)
 '(projectile-file-exists-local-cache-expire 300)
 '(projectile-globally-ignored-files '("TAGS" "GPATH" "GRTAGS" "GTAGS" "ID"))
 '(recentf-auto-cleanup 60)
 '(recentf-exclude
   '("~\\'" "\\`out\\'" "\\.log\\'" "^/[^/]*:" "\\.el\\.gz\\'"))
 '(recentf-max-saved-items 2000)
 '(safe-local-variable-values '((bug-reference-bug-regexp . "#\\(?2:[0-9]+\\)")))
 '(save-abbrevs 'silently)
 '(savehist-additional-variables
   '(tablist-named-filter file-name-history sr-history-registry kmacro-ring compile-histor regexp-search-ring search-ring))
 '(savehist-autosave-interval 60)
 '(savehist-ignored-variables '(load-history flyspell-auto-correct-ring kill-ring))
 '(scroll-bar-mode nil)
 '(tool-bar-mode nil)
 '(tramp-verbose 6 nil nil "Enable remote command traces")
 '(uniquify-buffer-name-style 'post-forward-angle-brackets nil (uniquify))
 '(use-package-enable-imenu-support t)
 '(user-full-name "Mark Colburn")
 '(user-initials "mhc")
 '(user-mail-address "colburn.mark@gmail.com")
 '(vc-annotate-background "#282c34")
 '(vc-annotate-color-map
   (list
    (cons 20 "#98be65")
    (cons 40 "#b4be6c")
    (cons 60 "#d0be73")
    (cons 80 "#ECBE7B")
    (cons 100 "#e6ab6a")
    (cons 120 "#e09859")
    (cons 140 "#da8548")
    (cons 160 "#d38079")
    (cons 180 "#cc7cab")
    (cons 200 "#c678dd")
    (cons 220 "#d974b7")
    (cons 240 "#ec7091")
    (cons 260 "#ff6c6b")
    (cons 280 "#cf6162")
    (cons 300 "#9f585a")
    (cons 320 "#6f4e52")
    (cons 340 "#5B6268")
    (cons 360 "#5B6268")))
 '(vc-annotate-very-old-color nil)
 '(visible-bell nil)
 '(yas-snippet-dirs '("~/.emacs.d/snippets"))
 '(yas-wrap-around-regon t))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:inherit nil :stipple nil :background "#212121" :foreground "#eeffff" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 110 :width normal :foundry "nil" :family "Iosevka"))))
 '(font-lock-constant-face ((t (:foreground "#C792EA"))))
 '(font-lock-keyword-face ((t (:foreground "#2BA3FF" :slant italic))))
 '(font-lock-preprocessor-face ((t (:inherit bold :foreground "#2BA3FF" :slant italic :weight normal))))
 '(font-lock-string-face ((t (:foreground "#C3E88D"))))
 '(font-lock-type-face ((t (:foreground "#FFCB6B"))))
 '(font-lock-variable-name-face ((t (:foreground "#FF5370"))))
 '(helm-rg-active-arg-face ((t (:foreground "LightGreen"))))
 '(helm-rg-file-match-face ((t (:foreground "LightGreen" :underline t))))
 '(helm-rg-preview-line-highlight ((t (:background "LightGreen" :foreground "black"))))
 '(linum ((t (:foreground "#8f8f8f" :height 0.8))))
 '(mode-line ((t (:background "#191919" :box nil))))
 '(mode-line-inactive ((t (:background "#282828" :foreground "#5B6268" :box nil))))
 '(nlinum-current-line ((t (:inherit linum :foreground "#daa520" :weight bold))))
 '(term ((t (:foreground "#fafafa")))))
